### ISSUE TITLE
Breaks custom protocol

### ISSUE THREAD

**Issue by adam-lynch** [murphydanger/gulp-minify-css#107]
A recent update has broken some of my CSS. This:

```css
div{background-image:url(app://abc.png)}
```

Get changed to this:

```css
div{background-image:url(app:/abc.png)}
```
