### ISSUE TITLE
after v0.4.2 gulp-minify-css is removing too much

### ISSUE THREAD

**Issue by Fetz** [murphydanger/gulp-minify-css#108]
before minification
````css
.rule {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
}
````

after minification 
````css
.rule {
  position: absolute;
  right: 0;
  bottom: 0;
}
```
