### ISSUE TITLE
IE8 compatibility: RGBA color plus separate color property creates invalid result

### ISSUE THREAD

**Issue by stevendesu** [murphydanger/gulp-minify-css#129]
I noticed this when I tried to concatenate and minify a number of CSS files which included a jQuery tourbus plugin. In this plugin there is CSS akin to the following:

```css
.element:before {
    border: solid rgba(0,0,0,0);
    /* ... */
    border-color: transparent;
}
```

Upon getting minified this produced:

```css
.element:before{border:rgba(0,0,0,0) solid transparent;}
```

In all common browsers the original works (`border-color` overrides the color in the shorthand property) however the minified version does not (invalid shorthand)

Doing a little bit of further investigation I found that this only happen with `{compatibility: 'ie8'}`
